spring:
  application:
    name: PBROGRT
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: GubaydulinRuslanTeimorovich #Студак добавить ---- BIB101200000
  expiration: 3600000